ms2ldaviz/motifdb/urls.py
from django.conf.urls import include, url
from motifdb import views

urlpatterns = [
    url(r'^$', views.index, name='motifdb_index'),
    url(r'^motif_set/(?P<motif_set_id>\w+)/$', views.motif_set,name='motif_set'),
    url(r'^motif/(?P<motif_id>\w+)/$', views.motif,name='motif'),
    url(r'^get_motif/(?P<motif_id>\w+)/$',views.get_motif,name='get_motif'),
    url(r'^update_annotation/(?P<motif_id>\w+)/$', views.update_annotation,name='update_annotation'),
    url(r'^start_motif_matching/(?P<experiment_id>\w+)/$', views.start_motif_matching,name='start_motif_matching'),
    url(r'^list_motifsets/$',views.list_motifsets,name = 'list_motifsets'),
    url(r'^get_motifset/(?P<motifset_id>\w+)/$', views.get_motifset,name='get_motifset'),
    url(r'^get_motifset/$', views.get_motifset_post,name='get_motifset_post'),
    url(r'^get_motifset_metadata/(?P<motifset_id>\w+)/$', views.get_motifset_metadata,name='get_motifset_metadata'),
    url(r'^initialise_api/$', views.initialise_api,name = 'initialise_api'),
    url(r'^create_motifset/$',views.create_motifset,name = 'create_motifset'),
    url(r'^choose_motifs/(?P<motif_set_id>\w+)/(?P<experiment_id>\w+)/$',views.choose_motifs,name = 'choose_motifs'),
    url(r'^edit_motifset_metadata/(?P<motif_set_id>\w+)/$',views.edit_motifset_metadata,name = 'edit_motifset_metadata'),
]

ms2ldaviz/ms2ldaviz/urls.py
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.contrib import admin

from . import views

app_name='ms2ldaviz'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^people/', views.people, name='people'),
    url(r'^about/', views.about, name='about'),
    url(r'^user_guide/', views.user_guide, name='user_guide'),
    url(r'^disclaimer/', views.disclaimer, name='disclaimer'),
    url(r'^confidence/', views.confidence, name='confidence'),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'^basicviz/', include('basicviz.urls')),
    # url(r'^annotation/', include('annotation.urls')),
    # url(r'^massbank/', include('massbank.urls')),
    # url(r'^options/', include('options.urls')),
    url(r'^registration/', include('registration.urls')),
    # url(r'^uploads/', include('uploads.urls')),
    # url(r'^decomposition/',include('decomposition.urls')),
    # url(r'^ms1analysis/', include('ms1analysis.urls')),
    url(r'^motifdb/', include('motifdb.urls')),
]

# for django debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ms2ldaviz/uploads/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from uploads import views

urlpatterns = [
    url(r'^create_experiment/$', views.create_experiment, name='create_experiment'),
    url(r'^process/$', views.process_experiment, name='process_experiment'),
    url(r'^ms1_format/$', TemplateView.as_view(template_name="uploads/ms1_format.html"), name='ms1_format'),
    url(r'^upload_experiment/$', views.upload_experiment, name='upload_experiment'),
    url(r'^upload_gensim_experiment/$', views.upload_gensim_experiment, name='upload_gensim_experiment'),
    url(r'^rerun/(?P<experiment_id>\w+)/$', views.rerun_experiment, name='rerun_experiment'),
]

ms2ldaviz/basicviz/models.py
import os
import jsonpickle
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


from .constants import EXPERIMENT_STATUS_CODE,EXPERIMENT_TYPE, EXPERIMENT_DECOMPOSITION_SOURCE, EXPERIMENT_MS2_FORMAT

from model_utils.managers import InheritanceManager



# Create your models here.
class MultiFileExperiment(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.CharField(max_length=1024, null=True)
    status = models.CharField(max_length=128, null=True)
    pca = models.TextField(null=True)
    alpha_matrix = models.TextField(null=True)
    degree_matrix = models.TextField(null=True)

    def __str__(self):
        return self.name


def get_upload_folder(instance, filename):
    upload_folder = "experiment_%s" % instance.pk
    return os.path.abspath(os.path.join(settings.MEDIA_ROOT, upload_folder, filename))


class BVFeatureSet(models.Model):
    name = models.CharField(max_length=64,unique = True)
    def __str__(self):
        bin_widths = {'binned_005':0.005,
                  'binned_01': 0.01,
                  'binned_05': 0.05,
                  'binned_1': 0.1,
                  'binned_5': 0.5}
        try:   
            return "{} Da".format(bin_widths[self.name])
        except:
            return self.name

    def get_width(self):
        bin_widths = {'binned_005':0.005,
                  'binned_01': 0.01,
                  'binned_05': 0.05,
                  'binned_1': 0.1,
                  'binned_5': 0.5}
        try:
            return bin_widths[self.name]
        except:
            return None
        




class Experiment(models.Model):
    
    name = models.CharField(max_length=128, unique=True)
    description = models.CharField(max_length=1024, null=True)

    ready_code, _ = EXPERIMENT_STATUS_CODE[1]
    status = models.CharField(max_length=128, choices=EXPERIMENT_STATUS_CODE,
                              null=True, default=ready_code)

    ms2lda_code, _ = EXPERIMENT_TYPE[0]
    experiment_type = models.CharField(max_length=128, choices=EXPERIMENT_TYPE,
                              null=True, default=ms2lda_code)

    ms2lda_format_code, _ = EXPERIMENT_MS2_FORMAT[0]
    experiment_ms2_format = models.CharField(max_length=128, choices=EXPERIMENT_MS2_FORMAT,
                              null=True, default=ms2lda_format_code)

    ms2_file = models.FileField(blank=True, null=True, upload_to=get_upload_folder)
    csv_file = models.FileField(blank=True, null=True, upload_to=get_upload_folder)

    csv_mz_column = models.CharField(blank = True, null = True, max_length=128, default='mz')
    # csv_rt_column = models.CharField(blank = True, null = True, max_length=128)
    csv_rt_units = models.CharField(blank = True, null = True, choices = [('minutes','minutes'),('seconds','seconds')],max_length=128,default = 'seconds')

    # these are the ones used for matching
    csv_id_column = models.CharField(blank = True, null = True, max_length=128)
    ms2_id_field = models.CharField(blank = True, null = True, max_length=128)
    ms2_name_field = models.CharField(blank = True,null = True,max_length=128)

    # I don't think this should be stored here
    # as it precludes the same experiment being decomposed multiple times
    no, _ = EXPERIMENT_DECOMPOSITION_SOURCE[0]
    decomposition_source = models.CharField(max_length=1, choices=EXPERIMENT_DECOMPOSITION_SOURCE,
                              null=False, default=no)

    # perhaps these parameters should be moved to a separate table?
    isolation_window = models.FloatField(null=True, default=0.5)
    mz_tol = models.FloatField(null=True, default=5)
    rt_tol = models.FloatField(null=True, default=10) # seconds
    min_ms1_rt = models.FloatField(null=True, default=3*60) # seconds
    max_ms1_rt = models.FloatField(null=True, default=21*60) # seconds
    min_ms2_intensity = models.FloatField(null=True, default=5000.0)

    # Same with these -- this model is getting a bit bloated
    filter_duplicates = models.BooleanField(null = False,default = False)
    min_ms1_intensity = models.FloatField(null = True,default=0.0)
    duplicate_filter_mz_tol = models.FloatField(null = True,default = 0.5)
    duplicate_filter_rt_tol = models.FloatField(null = True,default = 16)

    n_its = models.IntegerField(null = True,default = 1000)
    K = models.IntegerField(null=True, default=300)
    featureset = models.ForeignKey(BVFeatureSet,null = True, on_delete=models.CASCADE)

    has_magma_annotation = models.BooleanField(null = False, default = False)

    include_motifset = models.TextField(null = True)

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):

        # we want to separate the uploaded files into folders by experiment id
        # but initially there's no id yet ...
        if self.pk is None:

            # temporarily unset the uploaded files
            uploaded_csv_file = self.csv_file
            uploaded_ms2_file = self.ms2_file
            self.csv_file = None
            self.ms2_file = None

            # save first to get the id
            super(Experiment, self).save(*args, **kwargs)

            # set the uploaded files back
            self.csv_file = uploaded_csv_file
            self.ms2_file = uploaded_ms2_file

        # actually does the saving here
        super(Experiment, self).save(*args, **kwargs)


class Feature(models.Model):
    name = models.CharField(max_length=64)
    experiment = models.ForeignKey(Experiment,null=True, on_delete=models.CASCADE)
    min_mz = models.FloatField(null = True)
    max_mz = models.FloatField(null = True)
    featureset = models.ForeignKey(BVFeatureSet,null = True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class PublicExperiments(models.Model):
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)


class MultiLink(models.Model):
    multifileexperiment = models.ForeignKey(MultiFileExperiment, on_delete=models.CASCADE)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)


class ExtraUsers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class UserExperiment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    permission = models.CharField(max_length=24,null=False)



# Use cs.convert to convert an InChIKey to a mol file...
# cs = ChemSpider(settings.CHEMSPIDER_APIKEY)
# mol = cs.convert(ik,'InChIKey','mol')
class Document(models.Model):
    name = models.CharField(max_length=1024)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    metadata = models.CharField(max_length=4096, null=True)
    mol_string = models.TextField(null=True)

    def get_annotation(self):
        md = jsonpickle.decode(self.metadata)
        if 'annotation' in md:
            return md['annotation']
        else:
            return None

    def get_inchi(self):
        md = jsonpickle.decode(self.metadata)
        if 'InChIKey' in md:
            return md['InChIKey']
        else:
            return None

    def get_csid(self):
        md = jsonpickle.decode(self.metadata)
        if 'csid' in md:
            return md['csid']
        else:
            return None

    # this method probably doesn't work so well...
    def get_image_url(self):
        md = jsonpickle.decode(self.metadata)
        if 'csid' in md:
            # If this doc already has a csid, make the url
            return 'http://www.chemspider.com/ImagesHandler.ashx?id=' + str(self.csid)
        elif 'InChIKey' in md or 'inchikey' in md:
            # If it doesnt but it does have an InChIKey get the csid and make the image url
            # this code doesn't work...due to an upgrade in chemspider
            # if you want images, get the mol
            from chemspipy import ChemSpider
            cs = ChemSpider(settings.CHEMSPIDER_APIKEY)
            ikey = md.get('InChIKey',md.get('inchikey'))
            results = cs.search(ikey)
            if results:
                # Return the image_url and also save the csid
                csid = results[0].csid
                md['csid'] = csid
                self.metadata = jsonpickle.encode(md)
                self.save()
                return results[0].image_url
            else:
                return None
        else:
            # If it has neither, no image!
            return None

    def get_parentmass(self):
        md = jsonpickle.decode(self.metadata)
        if 'parentmass' in md:
            return md['parentmass']
        else:
            return None

    def get_mass(self):
        md = jsonpickle.decode(self.metadata)
        if 'precursormass' in md:
            return md['precursormass']
        elif 'precursor_mass' in md:
            return md['precursor_mass']
        elif 'parentmass' in md:
            return float(md['parentmass'])
        elif 'mz' in md:
            return md['mz']
        else:
            return None

    def get_rt(self):
        md = jsonpickle.decode(self.metadata)
        if 'rt' in md:
            return md['rt']
        else:
            return None

    def get_display_name(self):
        display_name = self.name
        md = jsonpickle.decode(self.metadata)
        if 'common_name' in md:
            display_name = md['common_name']
        elif 'annotation' in md:
            display_name = md['annotation']
        return display_name

    def get_logfc(self):
        md = jsonpickle.decode(self.metadata)
        if 'logfc' in md:
            return md['logfc']
        else:
            return None

    def get_user_cols(self):
        md = jsonpickle.decode(self.metadata)
        if 'user_cols' in md:
            return md['user_cols']
        else:
            return None

    rt = property(get_rt)
    logfc = property(get_logfc)

ms2ldaviz/templates/uploads/add_experiment.html
{% extends 'base.html' %}

{% load static %}

{% block head_block %}
{% endblock %}

{% block body_block %}

	<h3>Add a new experiment</h3>
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="/uploads/create_experiment">Create</a></li>
      <li role="presentation"><a href="/uploads/upload_experiment">Upload</a></li>
      {% if extra_user %}
      <li role="presentation"><a href="/uploads/upload_gensim_experiment">Upload gensim</a></li>
      {% endif %}
    </ul>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    When setting up LDA experiments, we recommend users to choose a number of relevant MotifDB motif sets
                    to find in your mass spectrometry fragmentation data with the parameter <i>Select zero or more motifsets
                    for initial model population</i>.
                </p>
                <p>
                    We also advise to add a few “free LDA motifs” with the parameter <i>Number of Mass2Motifs</i> to
                    cover the chemistry that does not match with any annotated Mass2Motif.
                </p>
                <p>
                    If an <a href="{%  url 'ms1_format' %}" target="_blank">MS1 CSV file</a> is provided, it will be used to seed the precursor peaks during the extraction of fragmentation spectra.
                    The uploaded MS2 file has to be in mzML/MSP/MGF format for now.
                </p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="experiment_form" method="post" action="/uploads/create_experiment/" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for hidden in experiment_form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in experiment_form.visible_fields %}
                        <p>{{ field.errors }}</p>
                        <p>  {{field.label}} {% if field.field.required %} * {% endif %} {{ field }}</p>
                    {% endfor %}
                    <input type="submit" name="submit" value="Submit Your Experiment" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </div>


{% endblock %}

{% block js_block %}
    <script type='text/javascript'>

//        function experiment_type_actions(){
//            var a = $('#id_experiment_type').val();

//            if (a === '0') { // ms2lda
//                $('#id_decomposition_source').parent().show();
//                $('#id_K').parent().show();
//                $('#id_decompose_from').parent().hide();

//            } else { // decomposition
//                $('#id_decomposition_source').parent().hide();
//                $('#id_K').parent().hide();
//                $('#id_decompose_from').parent().show();
//            }
//        }

        function experiment_ms2_format_actions(){
            var a = $('#id_experiment_ms2_format').val();
            if (a == '0') { // mzML
                $('#id_csv_file').parent().show();
                $('#id_isolation_window').parent().show();
                $('#id_mz_tol').parent().show();
                $('#id_rt_tol').parent().show();
                $('#id_min_ms1_rt').parent().show();
                $('#id_max_ms1_rt').parent().show();
                $('#id_filter_duplicates').parent().show();

            } else if(a == '1' || a == '2') { // msp or mgf
                $('#id_isolation_window').parent().hide();
                $('#id_min_ms1_rt').parent().hide();
                $('#id_max_ms1_rt').parent().hide();
                $('#id_filter_duplicates').parent().hide();
                $('#id_filter_duplicates').prop('checked', false);
                $('#id_duplicate_filter_mz_tol').parent().hide();
                $('#id_duplicate_filter_rt_tol').parent().hide();
            }
        }

        function filter_duplicates_actions(){
            if($('#id_filter_duplicates').is(":checked")){
                $('#id_duplicate_filter_mz_tol').parent().show();
                $('#id_duplicate_filter_rt_tol').parent().show();
            } else{
                $('#id_duplicate_filter_mz_tol').parent().hide();
                $('#id_duplicate_filter_rt_tol').parent().hide();
            }
        }

//        $('#id_experiment_type').on('change', function() {
//            experiment_type_actions();
//        });

        $('#id_experiment_ms2_format').on('change', function() {
            experiment_ms2_format_actions();
        });

        // Only show following two lines when ms1 duplicate checkbox is checked
        $('#id_filter_duplicates').click(function(){
            filter_duplicates_actions();
        });

        // initial state
        experiment_type_actions();
        filter_duplicates_actions();
        experiment_ms2_format_actions();

    </script>
{% endblock %}

ms2ldaviz/templates/uploads/ms1_format.html
{% extends 'base.html' %}

{% load static %}

{% block head_block %}
{% endblock %}

{% block body_block %}

	<h3>MS1 Peaklist File Format</h3>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <a name="ms1_format" />
                <p>
                    <a href="{% static "txt/example_peaklist.csv" %}">Download an example here</a>.
                </p>
                <p>
                    The required file format for the MS1 peak list is as follows:
                </p>
                <p>
                    A .CSV file with header line:
                </p>
                <blockquote>
                    ("..., mass, RT, samplename_1, samplename_2,..."), delimiter: '.
                </blockquote>
                <p>
                    The <strong>mass</strong> column must have the column header of either 'mass' or 'mz' (case-insensitive).
                    Retention time is assumed to be the column immediately after mass, and should be in seconds.
                    Any columns before <strong>mass</strong> (e.g. containing peak IDs from other software) will be ignored.
                </p>
                <p>
                    All columns after retention time will be interpreted as MS1 intensities, with one column per sample.
                    In the .CSV file, missing data can be stored as empty, e.g.
                </p>
                <blockquote>
                    123.45,,567.89
                </blockquote>
                <p>
                    or NA, e.g.
                </p>
                <blockquote>
                    123.45,NA,567.89
                </blockquote>
                <p>
                    Any intensities that are negative values, cannot be interpreted as a float, or are empty will be ignored
                    and not be stored for further analysis.
                </p>
            </div>
        </div>
    </div>


{% endblock %}

ms2ldaviz/templates/uploads/upload_experiment.html
{% extends 'base.html' %}

{% load static %}

{% block head_block %}
{% endblock %}

{% block body_block %}

	<h3>Add a new experiment</h3>
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="/uploads/create_experiment">Create</a></li>
      <li role="presentation" class="active"><a href="/uploads/upload_experiment">Upload</a></li>
      {% if extra_user %}
      <li role="presentation"><a href="/uploads/upload_gensim_experiment">Upload gensim</a></li>
      {% endif %}
    </ul>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    You can upload LDA experiments that have been performed locally in your computer
                    <a href="https://github.com/sdrogers/lda">(download script)</a>.
                </p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="experiment_form" method="post" action="/uploads/upload_experiment/" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for hidden in experiment_form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in experiment_form.visible_fields %}
                        <p>{{ field.errors }}</p>
                        <p>  {{field.label}} {% if field.field.required %} * {% endif %} {{ field }}</p>
                    {% endfor %}
                    <input type="submit" name="submit" value="Upload Your Experiment" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </div>


{% endblock %}

ms2ldaviz/templates/uploads/upload_gensim_experiment.html
{% extends 'base.html' %}

 {% load static %}

 {% block head_block %}
{% endblock %}

 {% block body_block %}

    <h3>Add a new experiment</h3>
    <ul class="nav nav-tabs">
      <li role="presentation"><a href="/uploads/create_experiment">Create</a></li>
      <li role="presentation"><a href="/uploads/upload_experiment">Upload</a></li>
      <li role="presentation" class="active"><a href="/uploads/upload_gensim_experiment">Upload gensim</a></li>
    </ul>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <p>
                    You can upload big LDA experiments that have been performed locally in your computer
                    <a href="https://github.com/iomega/ms2ldaviz/blob/pipenv-sqlite-redis/ms2ldaviz/run_gensim.py">(download script with `--ldaformat gensim` option)</a>.
                </p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <form id="experiment_form" method="post" action="/uploads/upload_gensim_experiment/" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for hidden in experiment_form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                     {% for field in experiment_form.visible_fields %}
                        <p>{{ field.errors }}</p>
                        <p>  {{field.label}} {% if field.field.required %} * {% endif %} {{ field }}</p>
                    {% endfor %}
                    <input type="submit" name="submit" value="Upload Your Experiment" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </div>


 {% endblock %}