ms2ldaviz/motifdb/urls.py
from django.conf.urls import include, url
from motifdb import views

urlpatterns = [
    url(r'^$', views.index, name='motifdb_index'),
    url(r'^motif_set/(?P<motif_set_id>\w+)/$', views.motif_set,name='motif_set'),
    url(r'^motif/(?P<motif_id>\w+)/$', views.motif,name='motif'),
    url(r'^get_motif/(?P<motif_id>\w+)/$',views.get_motif,name='get_motif'),
    url(r'^update_annotation/(?P<motif_id>\w+)/$', views.update_annotation,name='update_annotation'),
    url(r'^start_motif_matching/(?P<experiment_id>\w+)/$', views.start_motif_matching,name='start_motif_matching'),
    url(r'^list_motifsets/$',views.list_motifsets,name = 'list_motifsets'),
    url(r'^get_motifset/(?P<motifset_id>\w+)/$', views.get_motifset,name='get_motifset'),
    url(r'^get_motifset/$', views.get_motifset_post,name='get_motifset_post'),
    url(r'^get_motifset_metadata/(?P<motifset_id>\w+)/$', views.get_motifset_metadata,name='get_motifset_metadata'),
    url(r'^initialise_api/$', views.initialise_api,name = 'initialise_api'),
    url(r'^create_motifset/$',views.create_motifset,name = 'create_motifset'),
    url(r'^choose_motifs/(?P<motif_set_id>\w+)/(?P<experiment_id>\w+)/$',views.choose_motifs,name = 'choose_motifs'),
    url(r'^edit_motifset_metadata/(?P<motif_set_id>\w+)/$',views.edit_motifset_metadata,name = 'edit_motifset_metadata'),
]

ms2ldaviz/ms2ldaviz/urls.py
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.contrib import admin

from . import views

app_name='ms2ldaviz'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^people/', views.people, name='people'),
    url(r'^about/', views.about, name='about'),
    url(r'^user_guide/', views.user_guide, name='user_guide'),
    url(r'^disclaimer/', views.disclaimer, name='disclaimer'),
    url(r'^confidence/', views.confidence, name='confidence'),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'^basicviz/', include('basicviz.urls')),
    # url(r'^annotation/', include('annotation.urls')),
    # url(r'^massbank/', include('massbank.urls')),
    # url(r'^options/', include('options.urls')),
    url(r'^registration/', include('registration.urls')),
    # url(r'^uploads/', include('uploads.urls')),
    # url(r'^decomposition/',include('decomposition.urls')),
    # url(r'^ms1analysis/', include('ms1analysis.urls')),
    url(r'^motifdb/', include('motifdb.urls')),
]

# for django debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ms2ldaviz/motifdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import jsonpickle

from django.db import models
from django.contrib.auth.models import User
from basicviz.models import BVFeatureSet,Feature,Mass2Motif

# Create your models here.
class MDBMotifSet(models.Model):
    name = models.CharField(max_length=124,null=False,unique=True)
    description = models.TextField(null = True)
    featureset = models.ForeignKey(BVFeatureSet,null = True,blank=True, on_delete=models.CASCADE)
    metadata = models.TextField(null = True)
    owner = models.ForeignKey(User,null = True, on_delete=models.CASCADE)
    def __str__(self):
        ch = []
        if self.featureset:
            ch.append(str(self.featureset))
        try:
            md = jsonpickle.decode(self.metadata)
            ap = md['Analysis_Polarity']
            if ap:
                ch.append(ap)
            sample_type = md['Sample_type']
            if sample_type:
                ch.append(sample_type)
        except:
            pass
        return self.name + " ({})".format(", ".join(ch))
    def __repr__(self):
        return self.name

class MDBMotif(Mass2Motif):
    motif_set = models.ForeignKey(MDBMotifSet, on_delete=models.CASCADE)
    def save(self,*args,**kwargs):
        super(MDBMotif,self).save(*args,**kwargs)

    def get_comment(self):
        md = jsonpickle.decode(super(MDBMotif,self).metadata)
        return md.get('comment',None)

    comment = property(get_comment)
    

ms2ldaviz/motifdb/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import Q

from motifdb.models import MDBMotifSet
from basicviz.models import Experiment,BVFeatureSet,UserExperiment,PublicExperiments

class MatchMotifDBForm(forms.Form):
    motif_set = forms.ModelChoiceField(queryset = MDBMotifSet.objects.all(),required=True)
    min_score_to_save = forms.FloatField(required = True,initial=0.5)


class NewMotifSetForm(forms.Form):
    motifset_name = forms.CharField(max_length=1024,required = True, label = "Name")
    Motif_Name_Prefix = forms.CharField(max_length=10,required = True, label = "Motif Name Prefix")
    description = forms.CharField(required=True,widget = forms.Textarea)
    ms2lda_experiment = forms.ModelChoiceField(queryset=Experiment.objects.none(),
                                              required=False, label="Create from MS2LDA experiment")
    
    Analysis_Polarity = forms.ChoiceField(required = True,label = "Analysis_Polarity", choices = (
        ("positive ionisation mode","positive ionisation mode"),
        ("negative ionisation mode","negative ionisation mode"),
    )) 
    
    Analysis_IonizationSource = forms.ChoiceField(required = True,label = "Analysis_IonizationSource", choices = (
        ("electospray ionization","electospray ionization"),
        ("other","other"),
    ))
    # only show this if ms2lda_experiment isn't selected
    # bin_width = forms.DecimalField(required = False)

    Analysis_MassSpectrometer = forms.ChoiceField(required = True, label = "Analysis_MassSpectrometer",choices = (
        ("Maxis_Impact","Maxis_Impact"), 
        ("Maxis_ImpactHD","Maxis_ImpactHD"), 
        ("QExactive","QExactive"), 
        ("micrOTOF-Q II","micrOTOF-Q II"),
        ("Ion Trap","Ion Trap"), 
        ("Orbitrap","Orbitrap"), 
        ("Time-Of-Flight (ToF)","Time-Of-Flight (ToF)"),
        ("other high resolution instrument","other high resolution instrument"), 
        ("other low resolution instrument","other low resolution instrument"), 
        ("mixture","mixture"),
    ))

    Collision_Energy = forms.ChoiceField(label = "Collision_Energy",required = True, choices = (
        ("HCD","HCD"),
        ("CID","CID"),
        ("mixture","mixture"),
    ))

    Taxon_ID = forms.CharField(label = "Taxon_ID",required = False)

    Scientific_Name = forms.CharField(label = "Scientific_Name",required = False)

    Sample_Type = forms.CharField(label = "Sample_Type",required = False)

    Paper_URL = forms.CharField(label = "Paper_URL",required = False)

    Analysis_ChromatographyAndPhase = forms.ChoiceField(required = False, label = "Analysis_ChromatographyAndPhase", choices = (
        ("reverse phase (C18)","reverse phase (C18)"),
        ("reverse phase (C8)","reverse phase (C8)"),
        ("reverse phase (Phenyl-Hexyl)","reverse phase (Phenyl-Hexyl)"),
        ("normal phase (HILIC)","normal phase (HILIC)"), 
        ("mixed mode (Scherzo SM-C18)","mixed mode (Scherzo SM-C18)"),
        ("direct infusion (DI)","direct infusion (DI)"),
    ))

    Other_Information = forms.CharField(label = "Other_Information",widget=forms.Textarea,required= False)
    Massive_ID = forms.CharField(label = "Massive_ID",required = False)



    def __init__(self, user, *args, **kwargs):
        super(NewMotifSetForm, self).__init__(*args, **kwargs)

        fs = BVFeatureSet.objects.filter(name__in = ['binned_005','binned_01','binned_1'])
        ue = UserExperiment.objects.filter(user = user)
        pe = PublicExperiments.objects.all()
        experiments = Experiment.objects.filter(Q(featureset__in = fs), 
            (Q(id__in = [i.experiment.id for i in ue]) | Q(id__in = [p.experiment.id for p in pe])))
        self.fields['ms2lda_experiment'].queryset = experiments


class MetadataForm(forms.Form):
    motifset_name = forms.CharField(max_length=1024,required = True, label = "Name")
    # motif_name_prefix = forms.CharField(max_length=10,required = True, label = "Motif Name Prefix")
    description = forms.CharField(required=True,widget = forms.Textarea)
    # ms2lda_experiment = forms.ModelChoiceField(queryset=Experiment.objects.none(),
                                            #   required=False, label="Create from MS2LDA experiment")
    
    Analysis_Polarity = forms.ChoiceField(required = True,label = "Analysis_Polarity", choices = (
        ("positive ionisation mode","positive ionisation mode"),
        ("negative ionisation mode","negative ionisation mode"),
    )) 
    
    Analysis_IonizationSource = forms.ChoiceField(required = True,label = "Analysis_IonizationSource", choices = (
        ("electospray ionization","electospray ionization"),
        ("other","other"),
    ))
    # only show this if ms2lda_experiment isn't selected
    # bin_width = forms.DecimalField(required = False)

    Analysis_MassSpectrometer = forms.ChoiceField(required = True, label = "Analysis_MassSpectrometer",choices = (
        ("Maxis_Impact","Maxis_Impact"), 
        ("Maxis_ImpactHD","Maxis_ImpactHD"), 
        ("QExactive","QExactive"), 
        ("micrOTOF-Q II","micrOTOF-Q II"),
        ("Ion Trap","Ion Trap"), 
        ("Orbitrap","Orbitrap"), 
        ("Time-Of-Flight (ToF)","Time-Of-Flight (ToF)"),
        ("other high resolution instrument","other high resolution instrument"), 
        ("other low resolution instrument","other low resolution instrument"), 
        ("mixture","mixture"),
    ))

    Collision_Energy = forms.ChoiceField(required = True, choices = (
        ("HCD","HCD"),
        ("CID","CID"),
        ("mixture","mixture"),
    ))

    Taxon_ID = forms.CharField(label = "Taxon_ID",required = False)

    Scientific_Name = forms.CharField(required = False)

    Sample_Type = forms.CharField(required = False)

    Paper_URL = forms.CharField(label = "Paper_URL",required = False)

    Analysis_ChromatographyAndPhase = forms.ChoiceField(required = False, label = "Analysis_ChromatographyAndPhase", choices = (
        ("reverse phase (C18)","reverse phase (C18)"),
        ("reverse phase (C8)","reverse phase (C8)"),
        ("reverse phase (Phenyl-Hexyl)","reverse phase (Phenyl-Hexyl)"),
        ("normal phase (HILIC)","normal phase (HILIC)"), 
        ("mixed mode (Scherzo SM-C18)","mixed mode (Scherzo SM-C18)"),
        ("direct infusion (DI)","direct infusion (DI)"),
    ))

    Other_Information = forms.CharField(widget=forms.Textarea,required= False)
    Massive_ID = forms.CharField(label = "Massive_ID",required = False)



    # def __init__(self, user, *args, **kwargs):
    #     super(NewMotifSetForm, self).__init__(*args, **kwargs)

    #     fs = BVFeatureSet.objects.filter(name__in = ['binned_005','binned_01','binned_1'])
    #     ue = UserExperiment.objects.filter(user = user)
    #     pe = PublicExperiments.objects.all()
    #     experiments = Experiment.objects.filter(Q(featureset__in = fs), 
    #         (Q(id__in = [i.experiment.id for i in ue]) | Q(id__in = [p.experiment.id for p in pe])))
    #     self.fields['ms2lda_experiment'].queryset = experiments


class ChooseMotifs(forms.Form):
    motifs = forms.MultipleChoiceField(choices = (('a','a')),widget=forms.SelectMultiple())
    def __init__(self, motifs, *args, **kwargs):
        super(ChooseMotifs, self).__init__(*args, **kwargs)
        self.fields['motifs'].choices = motifs

ms2ldaviz/templates/motifdb/choose_motifs.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Welcome to motifDB{% endblock %}

{% block head_block %}
<style>
    #id_motifs {
    width: 800px;
    height: 400px;
    }
</style>

{% endblock %}

{% block body_block %}

    <h4>Select motifs for {{motif_set.name}} from {{experiment.name}}</h4>
    <div class="panel-group">
        {% if motif_form %}
            <form id="motif_form" method="post" action="/motifdb/choose_motifs/{{motif_set.id}}/{{experiment.id}}/">
                {% csrf_token %}
                {% for hidden in motif_form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            
                {% for field in motif_form.visible_fields %}
                    <p>{{ field.errors }}</p>
                    <p>{{ field }}
                    {{ field.label }}</p>
                {% endfor %}
                <input type="submit" name="submit" value="Choose motifs" class="btn btn-primary" />
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block js_block %}



{% endblock %}

ms2ldaviz/templates/motifdb/create_motifset.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Welcome to motifDB{% endblock %}

{% block head_block %}
{% endblock %}

{% block body_block %}

    <h4>Create a new MotifSet</h4>
    <div class="panel-group">
        {% if new_motifset_form %}
            <form id="new_motifset_form" method="post" action="/motifdb/create_motifset/">
                {% csrf_token %}
                {% for hidden in new_motifset_form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            
                {% for field in new_motifset_form.visible_fields %}
                    <p>{{ field.errors }}</p>
                    <p>{{ field }}
                    {{ field.label }}</p>
                {% endfor %}
                <input type="submit" name="submit" value="Create MotifSet" class="btn btn-primary" />
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block js_block %}



{% endblock %}

ms2ldaviz/templates/motifdb/edit_motif_set_metadata.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Welcome to motifDB{% endblock %}

{% block head_block %}
{% endblock %}

{% block body_block %}

    <h4>Edit metadata for {{motifset.name}}</h4>
    <div class="panel-group">
        {% if mdbform %}
            <form id="new_motifset_form" method="post" action="/motifdb/edit_motifset_metadata/{{motifset.id}}/">
                {% csrf_token %}
                {% for hidden in mdbform.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            
                {% for field in mdbform.visible_fields %}
                    <p>{{ field.errors }}</p>
                    <p>{{ field }}
                    {{ field.label }}</p>
                {% endfor %}
                <input type="submit" name="submit" value="Save changes" class="btn btn-primary" />
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block js_block %}



{% endblock %}

ms2ldaviz/templates/motifdb/index.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}Welcome to motifDB{% endblock %}

{% block head_block %}
    <style>
    </style>
{% endblock %}

{% block body_block %}

    <h4>Welcome to motifDB</h4>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <h5>Create a new motifset</h5>
                <p>
                    Once MS2LDA experiments have been created and annotated, you could use them to create your own
                    motifset
                    on MotifDB. The patterns of fragments and neutral losses from these motifsets could be selected for
                    unsupervised
                    substructural discovery on new data when running LDA experiments on this website and on
                    <a href="https://ccms-ucsd.github.io/GNPSDocumentation/ms2lda/" target="_blank">GNPS-MS2LDA
                        workflow</a>.
                </p>
                <p><a class="btn btn-primary" href="/motifdb/create_motifset">Create your own motifset on MotifDB from
                    one of your own MS2LDA experiments</a></p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h5>The following motif sets have been contributed by the community</h5>
                <table class="table">
                    <tr>
                        <th>Motifset Name</th>
                        <th width="20%">Feature Set</th>
                        <th>Description</th>
                        <th width="10%">No. motifs</th>
                    </tr>
                    {% for motif_set, count in motif_sets %}
                        <tr>
                            <td><a href="/motifdb/motif_set/{{ motif_set.id }}">{{ motif_set.name }}</a></td>
                            <td>{{ motif_set.featureset }}</td>
                            <td>{{ motif_set.description }}</td>
                            <td>{{ count }} motifs</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h5>API Access</h5>
                <p>MotifDB provides a RESTful API that allows programmatic access to motif sets and their metadata. This enables integration with other tools and workflows for mass spectrometry data analysis.</p>

                <h6>Available Endpoints</h6>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Endpoint</th>
                            <th>Method</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><code>http://ms2lda.org/motifdb/list_motifsets</code></td>
                            <td>GET</td>
                            <td>Returns a JSON dictionary of available motif sets and their IDs</td>
                        </tr>
                        <tr>
                            <td><code>http://ms2lda.org/motifdb/get_motifset/{ID}</code></td>
                            <td>GET</td>
                            <td>Returns a JSON object with all motifs in the specified motifset</td>
                        </tr>
                        <tr>
                            <td><code>http://ms2lda.org/motifdb/get_motifset_metadata/{ID}</code></td>
                            <td>GET</td>
                            <td>Returns metadata for motifs in the specified motifset</td>
                        </tr>
                        <tr>
                            <td><code>http://ms2lda.org/motifdb/get_motifset</code></td>
                            <td>POST</td>
                            <td>Returns motifs and metadata for multiple motifsets</td>
                        </tr>
                        <tr>
                            <td><code>http://ms2lda.org/motifdb/initialise_api</code></td>
                            <td>GET</td>
                            <td>Returns a CSRF token required for POST requests</td>
                        </tr>
                    </tbody>
                </table>

                <h6>Usage Instructions</h6>
                <p>
                    <strong>Single Motifset Access:</strong> To access a single motifset, send a GET request to 
                    <code>http://ms2lda.org/motifdb/get_motifset/{ID}</code>, where <code>{ID}</code> is the ID obtained 
                    from the motifset list. This returns all motifs in that motifset.
                </p>
                <p>
                    <strong>Multiple Motifsets:</strong> To retrieve motifs and metadata for multiple motifsets, send a POST request to 
                    <code>http://ms2lda.org/motifdb/get_motifset</code> with a payload containing:
                </p>
                <ul>
                    <li><code>motifset_id_list</code>: A list of motifset IDs you want to retrieve</li>
                    <li><code>csrfmiddlewaretoken</code>: A valid CSRF token (obtained from <code>/motifdb/initialise_api</code>)</li>
                    <li><code>filter</code>: Set to "True" to filter duplicate motifs (optional)</li>
                    <li><code>filter_threshold</code>: Cosine score threshold for filtering (default: 0.95, optional)</li>
                </ul>

                <h6>Python Example</h6>
                <pre>
import requests

server_url = "http://ms2lda.org"

# Get the list of available motif sets
output = requests.get(server_url + '/motifdb/list_motifsets')
motifset_list = output.json()

# Get a CSRF token for POST requests
url = server_url + '/motifdb/initialise_api'
client = requests.session()
token = client.get(url).json()['token']

# Prepare data for POST request
url = server_url + '/motifdb/get_motifset/'
data = {'csrfmiddlewaretoken': token}

# Specify motifsets of interest
massbank_motifset = 'Massbank library derived Mass2Motifs'
gnps_motifset = 'GNPS library derived Mass2Motifs'

massbank_id = motifset_list[massbank_motifset]
gnps_id = motifset_list[gnps_motifset]

# Example 1: Get multiple motifsets with filtering
data['motifset_id_list'] = [massbank_id, gnps_id]
data['filter'] = "True"
data['filter_threshold'] = 0.95  # Default value - not required
output = client.post(url, data=data).json()
print('Retrieved {} motifs and {} metadata entries'.format(
    len(output['motifs']), len(output['metadata'])))

# Example 2: Get metadata for a single motifset
url = server_url + '/motifdb/get_motifset_metadata/{}/'.format(massbank_id)
output = requests.get(url)
motif_metadata = output.json()
print('First 5 metadata entries:')
for k in list(motif_metadata.keys())[:5]:
    print(k)
    print(motif_metadata[k])
                </pre>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}

    <script>
        $(function () {
            $("#accordion").accordion({
                collapsible: true,
                heightStyle: "content",
                active: false
            });
        });
        $(function () {
            $("#accordion2").accordion({
                collapsible: true,
                heightStyle: "content",
                active: false
            });
        });
        $(function () {
            $("#accordion3").accordion({
                collapsible: true,
                heightStyle: "content",
                active: false
            });
        });
        $(function () {
            $("#tabs").tabs();
        });
    </script>

{% endblock %}

ms2ldaviz/templates/motifdb/motif_set.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block title %}Welcome to motifDB{% endblock %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'js/dataTables/dataTables.bootstrap.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'js/dataTables/buttons.dataTables.min.css' %}" type="text/css">
{% endblock %}

{% block body_block %}

    <h4>{{motif_set.name}}</h4>
    <div class="panel-group">

        <div class="panel panel-default">
            <div class="panel-body">
                <p>Description: {{motif_set.description}}</p>
                <p>Metadata:</p>
                <ul>
                    {% for key,value in metadata.items %}
                        <ul><b>{{key}}:</b> {{value}}</ul>
                    {% endfor %}
                </ul>
                <div>
                    {% if correct_user %}
                        <a href="/motifdb/edit_motifset_metadata/{{motif_set.id}}">Edit metadata</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table" id="motiftable">
                        <thead>
                        <tr>
                            <th>Motif</th>
                            <th>Annotation</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for motif in motifs %}
                            <tr>
                                <td><a href="/motifdb/motif/{{motif.id}}">{{ motif.name }}</a></td>
                                <td>{{ motif.annotation }}</td>
                                <td><a href="https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:MOTIFDB::accession:{{ motif.id}}">Resolver: mzspec:MOTIFDB::accession:{{ motif.id}}</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <p><a href="/motifdb">Return to motifDB</a></p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js_block %}

<script src="{% static 'js/dataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'js/dataTables/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'js/dataTables/buttons.html5.min.js' %}"></script>

<script>  
    $('#motiftable').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'csv',
        ],
        "order": [[1, "desc"]],
    });
</script>

{% endblock %}

ms2ldaviz/templates/motifdb/start_match_motifs.html
{% extends 'base.html' %}

{% load static %}

{% block head_block %}

{% endblock %}

{% block body_block %}

<h4>Motif matches for {{experiment}}</h4>

<div>This feature allows Mass2Motifs in one experiment to be searched against those in another. The searching involves two steps:</div>
<div>
    <ul>
        <li>Matching the features</li>
        <li>Computing the cosine similarity of the Mass2Motifs in the matched feature space</li>
    </ul>
</ul>
</div>
<div>Choose an experiment to compare against in the form below and pick a minimum threshold for storing found links. Note that once found, links need to be verified (choose manage motif matches for the experiment of interest from the main menu).</div>

<form id="match_form" method="post" action="/motifdb/start_motif_matching/{{experiment.id}}/">
    {% csrf_token %}
    {% for hidden in match_motif_form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in match_motif_form.visible_fields %}
        <p>{{ field.errors }}</p>
        <p>{{ field }}
        {{ field.label }}</p>
    {% endfor %}
    <input type="submit" name="submit" value="Start matching" class="btn btn-primary" />
 </form>
 


{% endblock %}

{% block js_block %}

{% endblock %}